<a href="https://colab.research.google.com/github/tainabh/analise_titanic/blob/main/analise_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**ANÁLISE EXPLORATÓRIA DE DADOS DO TITANIC**

A presente análise exploratória tem como objetivo compreender o comportamento geral dos dados do conjunto Titanic, identificando padrões, relações entre variáveis e possíveis fatores associados à sobrevivência dos passageiros.

A partir da exploração do dataset, serão realizadas etapas de importação, organização e tratamento dos dados, além da geração de estatísticas descritivas e visualizações gráficas.

**Perguntas a serem respondidas na análise:**

	1. Qual a proporção de passageiros que sobreviveram ao naufrágio?
	2. Existe relação entre a classe do passageiro e a sobrevivência?
	3. O sexo do passageiro influenciou na chance de sobreviver?
	4. A idade teve impacto na sobrevivência?
	5. O tamanho da família a bordo teve alguma relação com a sobrevivência?

A partir dessas análises, busca-se obter insights que ajudem a compreender melhor os fatores que podem ter influenciado a sobrevivência dos passageiros do Titanic.

# 1. IMPORTANDO A BIBLIOTECA PANDAS

In [92]:
import pandas as pd

# 2. CARREGAMENTO DOS DADOS

In [93]:
df_titanic = pd.read_csv('/titanic_dataset.csv')


# Verificando as linhas iniciais da tabela
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [94]:
# Verificando as últimas linhas da tabela

df_titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

# 3.  ANÁLISES GERAIS ANTES DO TRATAMENTO E LIMPEZA DOS DADOS

In [95]:
# Analisando amostra aleatória

df_titanic.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
807,808,0,3,"Pettersson, Miss. Ellen Natalia",female,18.0,0,0,347087,7.775,NaN,S

In [96]:
# Analisando as informações

df_titanic.info()

# 891 passageiros à bordo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [97]:
# Descrevendo as informações

df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 4. TRATAMENTO E LIMPEZA INICIAL DOS DADOS

In [117]:
# Verificando a existência de linhas duplicadas

total_duplicadas = df_titanic.duplicated().sum()
total_duplicadas

np.int64(0)

In [99]:

# Traduzindo as colunas

map_titanic = {
    'PassengerId': 'id_passageiro',
    'Survived': 'sobrevivente',
    'Pclass': 'classe',
    'Name': 'nome',
    'Sex': 'genero',
    'Age': 'idade',
    'SibSp': 'qtd_irmaos_conjuges',
    'Parch': 'qtd_pais_filhos',
    'Ticket': 'bilhete',
    'Fare': 'preco_passagem',
    'Cabin': 'cabine',
    'Embarked': 'porto_embarque'
}

# Aplicando as renomeações

df_titanic.rename(columns=map_titanic, inplace=True)
print ("Colunas traduzidas para o português.")

Colunas traduzidas para o português.

In [100]:
# Transformando a coluna "sobrevivente", alterando as variáveis para "sim" ou "não"

df_titanic['sobrevivente'] = df['sobrevivente'].astype(str)
df_titanic['sobrevivente'] = df_titanic['sobrevivente'].map({'0': 'Não', '1': 'Sim'})

df_titanic['sobrevivente'].value_counts()

sobrevivente
Não    549
Sim    342
Name: count, dtype: int64

In [101]:
# Transformando a coluna "gênero"

df_titanic['genero'] = df_titanic['genero'].map({'male': 'Masculino', 'female': 'Feminino'})

df_titanic.head()

,id_passageiro,sobrevivente,classe,nome,genero,idade,qtd_irmaos_conjuges,qtd_pais_filhos,bilhete,preco_passagem,cabine,porto_embarque
0,1,Não,3,"Braund, Mr. Owen Harris",Masculino,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Sim,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Feminino,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Sim,3,"Heikkinen, Miss. Laina",Feminino,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Sim,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Feminino,35.0,1,0,113803,53.1000,C123,S
4,5,Não,3,"Allen, Mr. William Henry",Masculino,35.0,0,0,373450,8.0500,NaN,S

In [110]:
# Transformando a coluna idade, tratando os dados nulos:

df_titanic['idade'].isnull().sum()

nulos_pct = df_titanic.isnull().mean() * 100
nulos_pct

# A coluna idade apresenta 177 valores ausentes. Como a remoção dessas linhas resultaria em perda significativa de dados, optou-se por preencher os valores faltantes utilizando a mediana das idades dos passageiros.

df_titanic['idade'] = df_titanic['idade'].fillna(df_titanic['idade'].median())

# Transformando a coluna em valores inteiros

df_titanic['idade'] = df_titanic['idade'].astype(int)

In [ ]:
# Criando a coluna "tamanho_familia" e excluindo as colunas "qtd_irmaos_conjuges" e	"qtd_pais_filhos"