<a href="https://colab.research.google.com/github/tainabh/analise_titanic/blob/main/analise_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [303]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**ANÁLISE EXPLORATÓRIA DE DADOS DO TITANIC**

A presente análise exploratória tem como objetivo compreender o comportamento geral dos dados do conjunto Titanic, identificando padrões, relações entre variáveis e possíveis fatores associados à sobrevivência dos passageiros.

A partir da exploração do dataset, serão realizadas etapas de importação, organização e tratamento dos dados, além da geração de estatísticas descritivas e visualizações gráficas.

**Perguntas a serem respondidas na análise:**

1. Qual é a proporção de passageiros que sobreviveram ao naufrágio?
2. Existe relação entre a classe do passageiro e a probabilidade de sobrevivência?
3. O sexo do passageiro influenciou nas chances de sobrevivência?
4. A idade teve impacto na probabilidade de sobrevivência?
5. O tamanho da família a bordo apresenta alguma relação com a sobrevivência?
6. O valor pago pela passagem influenciou na chance de sobrevivência?
7. O porto de embarque teve alguma influência na sobrevivência dos passageiros?

A partir dessas análises, busca-se obter insights que ajudem a compreender melhor os fatores que podem ter influenciado a sobrevivência dos passageiros do Titanic.

# 1. IMPORTANDO A BIBLIOTECA PANDAS

In [304]:
import pandas as pd

# 2. CARREGAMENTO DOS DADOS

In [305]:
df_titanic = pd.read_csv('/titanic_dataset.csv')


# Verificando as linhas iniciais da tabela
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [306]:
# Verificando as últimas linhas da tabela

df_titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

# 3.  ANÁLISES GERAIS ANTES DO TRATAMENTO E LIMPEZA DOS DADOS

In [307]:
# Analisando amostra aleatória

df_titanic.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0,B96 B98,S

In [308]:
# Analisando as informações

df_titanic.info()

# 891 passageiros à bordo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [309]:
# Descrevendo as informações

df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 4. TRATAMENTO E LIMPEZA INICIAL DOS DADOS

In [310]:
# Verificando a existência de linhas duplicadas

total_duplicadas = df_titanic.duplicated().sum()
total_duplicadas

np.int64(0)

In [311]:

# Traduzindo as colunas

map_titanic = {
    'PassengerId': 'id_passageiro',
    'Survived': 'sobrevivente',
    'Pclass': 'classe',
    'Name': 'nome',
    'Sex': 'genero',
    'Age': 'idade',
    'SibSp': 'qtd_irmaos_conjuges',
    'Parch': 'qtd_pais_filhos',
    'Ticket': 'bilhete',
    'Fare': 'preco_passagem',
    'Cabin': 'cabine',
    'Embarked': 'porto_embarque'
}

# Aplicando as renomeações

df_titanic.rename(columns=map_titanic, inplace=True)
print ("Colunas traduzidas para o português.")

Colunas traduzidas para o português.

In [312]:
# Transformando a coluna "sobrevivente", alterando as variáveis para "sim" ou "não"

df_titanic['sobrevivente'] = df_titanic['sobrevivente'].astype(str)
df_titanic['sobrevivente'] = df_titanic['sobrevivente'].map({'0': 'Não', '1': 'Sim'})

df_titanic['sobrevivente'].value_counts()

sobrevivente
Não    549
Sim    342
Name: count, dtype: int64

In [313]:
# A coluna "classe" será mantida

df_titanic['classe']. value_counts ()

classe
3    491
1    216
2    184
Name: count, dtype: int64

In [314]:
# A coluna nome será removida do conjunto de dados a fim de preservar a identidade dos passageiros, evitando a exposição de informações individuais que não são necessárias para a análise.

df_titanic=df_titanic.drop(columns=['nome'])

In [315]:
# Transformando a coluna "gênero"

df_titanic['genero'] = df_titanic['genero'].map({'male': 'Masculino', 'female': 'Feminino'})

In [316]:
# A coluna "idade" apresenta 177 valores ausentes. Como a remoção dessas linhas resultaria em uma perda significativa de dados, optou-se por manter os valores NaN. Além disso, a coluna foi mantida no tipo float64, pois esse formato permite a realização de operações estatísticas e cálculos mesmo na presença de valores ausentes, sem comprometer as análises.

In [317]:
# Criando a coluna "tamanho_familia" com base nas colunas "qtd_irmaos_conjuges" e "qtd_pais_filhos"
df_titanic['tamanho_familia'] = df_titanic['qtd_irmaos_conjuges'] + df_titanic['qtd_pais_filhos']

# Removendo as colunas originais para limpeza de dados

df_titanic=df_titanic.drop(columns=['qtd_irmaos_conjuges', 'qtd_pais_filhos'])

In [318]:
# A coluna "bilhete" será removida por não ter relevância nas análises estatísticas a serem realizadas no momento.

df_titanic = df_titanic.drop(columns=['bilhete'])

In [319]:
# A coluna "preco_passagem" será mantida.

In [320]:
# A coluna cabine possui informações em apenas 204 registros do conjunto de dados. Devido à grande quantidade de valores ausentes, optou-se pela exclusão dessa coluna, pois sua manutenção poderia comprometer a qualidade das análises.

df_titanic = df_titanic.drop(columns=['cabine'])

In [321]:
# A coluna "porto_embarque" apresenta 2 valores ausentes. Como a quantidade de registros faltantes é pequena, optou-se por manter a coluna e substituir os valores ausentes pela categoria “informação não obtida”.

df_titanic['porto_embarque'] = df_titanic['porto_embarque'].fillna('Informação não obtida')

df_titanic['porto_embarque']. value_counts ()

porto_embarque
S                        644
C                        168
Q                         77
Informação não obtida      2
Name: count, dtype: int64

In [324]:
# Versão final da tabela após tratamento e limpeza dos dados

df_titanic.head()

,id_passageiro,sobrevivente,classe,genero,idade,preco_passagem,porto_embarque,tamanho_familia
0,1,Não,3,Masculino,22.0,7.2500,S,1
1,2,Sim,1,Feminino,38.0,71.2833,C,1
2,3,Sim,3,Feminino,26.0,7.9250,S,0
3,4,Sim,1,Feminino,35.0,53.1000,S,1
4,5,Não,3,Masculino,35.0,8.0500,S,0

# 5. TRATAMENTO E LIMPEZA INICIAL DOS DADOS